"use client";
import {useEffect,useMemo,useState} from "react";
type Detail={signal:{avg_entry:number;current_price:number|null};trades:Array<{id:string;wallet:string;username:string|null;price:number;notional:number;traded_at:string;side:string}>;events:Array<{id:string;detected_at:string;trigger_reason:string}>;priceHistory:{available:boolean;points:Array<{t:number;p:number}>;reason:string|null}};
const short=(w:string)=>w.length>12?`${w.slice(0,6)}…${w.slice(-4)}`:w;
export function SignalTimeline({id}:{id:string}){
 const [detail,setDetail]=useState<Detail|null>(null),[error,setError]=useState("");
 useEffect(()=>{let active=true;setDetail(null);setError("");fetch(`/api/signals/${encodeURIComponent(id)}`,{cache:"no-store"}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);if(active)setDetail(b)}).catch(e=>active&&setError(e.message));return()=>{active=false}},[id]);
 const chart=useMemo(()=>{if(!detail?.priceHistory.available)return null;const points=detail.priceHistory.points;if(!points.length)return null;const times=[...points.map(p=>p.t*1000),...detail.trades.map(t=>new Date(t.traded_at).getTime())];const minT=Math.min(...times),maxT=Math.max(...times);const prices=[...points.map(p=>Number(p.p)),Number(detail.signal.avg_entry),...(detail.signal.current_price==null?[]:[Number(detail.signal.current_price)])];const minP=Math.min(...prices),maxP=Math.max(...prices);const x=(t:number)=>6+88*(t-minT)/Math.max(1,maxT-minT),y=(p:number)=>88-76*(p-minP)/Math.max(.01,maxP-minP);return {points,path:points.map((p,i)=>`${i?"L":"M"}${x(p.t*1000).toFixed(2)},${y(Number(p.p)).toFixed(2)}`).join(" "),x,y,minP,maxP};},[detail]);
 if(error)return <div className="chart-unavailable"><b>Timeline unavailable</b><span>{error}</span></div>;
 if(!detail)return <div className="chart-unavailable"><span>Loading market timeline…</span></div>;
 if(!chart)return <div className="chart-unavailable"><b>Historical price unavailable</b><span>{detail.priceHistory.reason||"No official price history was returned. Stored entries remain unchanged."}</span></div>;
 return <section className="timeline"><div className="subhead"><b>Entry timeline</b><span>Official price history · stored whale flow</span></div><svg viewBox="0 0 100 100" role="img" aria-label="Market price and whale entry timeline" preserveAspectRatio="none"><line x1="6" x2="94" y1={chart.y(Number(detail.signal.avg_entry))} y2={chart.y(Number(detail.signal.avg_entry))} className="entry-reference"/><path d={chart.path}/>{detail.events.map((e,i)=><line key={e.id} x1={chart.x(new Date(e.detected_at).getTime())} x2={chart.x(new Date(e.detected_at).getTime())} y1="8" y2="90" className="event-line"><title>{i===0?"Signal first detected":e.trigger_reason.replaceAll("_"," ")} · {new Date(e.detected_at).toLocaleString()}</title></line>)}{detail.trades.filter(t=>t.side==="BUY").map(t=><circle key={t.id} cx={chart.x(new Date(t.traded_at).getTime())} cy={chart.y(Number(t.price))} r={Math.min(3.2,1.2+Math.sqrt(Number(t.notional))/120)}><title>{t.username?`${t.username} · `:""}{short(t.wallet)} · entry {(Number(t.price)*100).toFixed(1)}¢ · ${Number(t.notional).toLocaleString()} · {new Date(t.traded_at).toLocaleString()}</title></circle>)}{detail.signal.current_price!=null&&<circle className="current-dot" cx="94" cy={chart.y(Number(detail.signal.current_price))} r="2"><title>Current price {(Number(detail.signal.current_price)*100).toFixed(1)}¢</title></circle>}</svg><div className="chart-legend"><span><i className="legend-line"/>Market</span><span><i className="legend-buy"/>Whale buy</span><span><i className="legend-event"/>Signal event</span><b>Weighted entry {(Number(detail.signal.avg_entry)*100).toFixed(1)}¢</b></div></section>;
}
